/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IsPalindrome {
    }
}
declare global {
    interface HTMLIsPalindromeElement extends Components.IsPalindrome, HTMLStencilElement {
    }
    var HTMLIsPalindromeElement: {
        prototype: HTMLIsPalindromeElement;
        new (): HTMLIsPalindromeElement;
    };
    interface HTMLElementTagNameMap {
        "is-palindrome": HTMLIsPalindromeElement;
    }
}
declare namespace LocalJSX {
    interface IsPalindrome {
    }
    interface IntrinsicElements {
        "is-palindrome": IsPalindrome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "is-palindrome": LocalJSX.IsPalindrome & JSXBase.HTMLAttributes<HTMLIsPalindromeElement>;
        }
    }
}
