/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CicdApp {
    }
    interface CicdFooter {
    }
    interface CicdHeader {
    }
    interface CicdMain {
    }
    interface IsPalindrome {
    }
}
declare global {
    interface HTMLCicdAppElement extends Components.CicdApp, HTMLStencilElement {
    }
    var HTMLCicdAppElement: {
        prototype: HTMLCicdAppElement;
        new (): HTMLCicdAppElement;
    };
    interface HTMLCicdFooterElement extends Components.CicdFooter, HTMLStencilElement {
    }
    var HTMLCicdFooterElement: {
        prototype: HTMLCicdFooterElement;
        new (): HTMLCicdFooterElement;
    };
    interface HTMLCicdHeaderElement extends Components.CicdHeader, HTMLStencilElement {
    }
    var HTMLCicdHeaderElement: {
        prototype: HTMLCicdHeaderElement;
        new (): HTMLCicdHeaderElement;
    };
    interface HTMLCicdMainElement extends Components.CicdMain, HTMLStencilElement {
    }
    var HTMLCicdMainElement: {
        prototype: HTMLCicdMainElement;
        new (): HTMLCicdMainElement;
    };
    interface HTMLIsPalindromeElement extends Components.IsPalindrome, HTMLStencilElement {
    }
    var HTMLIsPalindromeElement: {
        prototype: HTMLIsPalindromeElement;
        new (): HTMLIsPalindromeElement;
    };
    interface HTMLElementTagNameMap {
        "cicd-app": HTMLCicdAppElement;
        "cicd-footer": HTMLCicdFooterElement;
        "cicd-header": HTMLCicdHeaderElement;
        "cicd-main": HTMLCicdMainElement;
        "is-palindrome": HTMLIsPalindromeElement;
    }
}
declare namespace LocalJSX {
    interface CicdApp {
    }
    interface CicdFooter {
    }
    interface CicdHeader {
    }
    interface CicdMain {
    }
    interface IsPalindrome {
    }
    interface IntrinsicElements {
        "cicd-app": CicdApp;
        "cicd-footer": CicdFooter;
        "cicd-header": CicdHeader;
        "cicd-main": CicdMain;
        "is-palindrome": IsPalindrome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cicd-app": LocalJSX.CicdApp & JSXBase.HTMLAttributes<HTMLCicdAppElement>;
            "cicd-footer": LocalJSX.CicdFooter & JSXBase.HTMLAttributes<HTMLCicdFooterElement>;
            "cicd-header": LocalJSX.CicdHeader & JSXBase.HTMLAttributes<HTMLCicdHeaderElement>;
            "cicd-main": LocalJSX.CicdMain & JSXBase.HTMLAttributes<HTMLCicdMainElement>;
            "is-palindrome": LocalJSX.IsPalindrome & JSXBase.HTMLAttributes<HTMLIsPalindromeElement>;
        }
    }
}
